spring.application.name=doc-ocr-spring-backend

# OCR Space API Configuration
ocr.space.api.url=https://api.ocr.space/parse/image
ocr.space.api.key=${OCR_SPACE_API_KEY:helloworld}

# Upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
ocr.upload.allowed-content-types=application/pdf

# Basic auth
spring.security.user.name=${APP_USER:admin}
spring.security.user.password=${APP_PASSWORD:admin}

# Datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/doc_ocr}
spring.datasource.username=${DB_USER:doc_ocr}
spring.datasource.password=${DB_PASSWORD:doc_ocr}
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.file.name=logs/app.log